"""Generate game_bss.inc (included by asm/blit.asm) from asm/game_bss.txt.

game_bss.txt lists every uninitialized game variable in original address order:

    plain   004213c8  4      gdpidLocalPlayer
    common  004280e0  32768  giInputBuffer
    field   00447dad  4      giShakeXOffset

'plain' variables become ordinary _BSS storage in the OMF object, which LINK places at the start
of .bss (before LIBC's .bss).  'common' variables become communal definitions (COMDEF); LINK
allocates those after all .bss sections, pushing each newly seen one to the front of its list,
so they are emitted in reverse order.  LINK aligns a communal variable to
min(next power of two >= size, 32); the table is checked against that rule.

'field' rows are names the C code uses for a member of a larger variable (for instance the
unaligned members of the packed kgt_stage behind gkgtLoadedStage, or a second name for the same
array).  They take no storage: a field inside a plain variable becomes a label relative to it, a
field inside a common one an absolute symbol at its original address (the executable has no base
relocations, so that is exact as long as the common itself lands at its original address, which
the linker map check covers).  The size is informational (and checked to fit in the container).
"""
import os, sys


def load(path):
    rows = []
    for line in open(path, encoding="utf-8"):
        line = line.split("#")[0].split()
        if not line:
            continue
        region, addr, size, name = line[0], int(line[1], 16), int(line[2], 0), line[3]
        if region not in ("plain", "common", "field"):
            raise SystemExit("game_bss.txt: bad region %r for %s" % (region, name))
        rows.append((region, addr, size, name))
    return rows


def container(rows, a, s):
    for g, a2, s2, n2 in rows:
        if g != "field" and a2 <= a and a + s <= a2 + s2:
            return g, a2, n2
    return None


def check(rows):
    errors = []
    names = set()
    for region in ("plain", "common"):
        r = [x for x in rows if x[0] == region]
        for (g, a, s, n), (g2, a2, s2, n2) in zip(r, r[1:]):
            if a + s > a2:
                errors.append("%s overlaps %s" % (n, n2))
            if a2 < a:
                errors.append("%s is out of address order" % n2)
        if region == "common":
            prev_end = None
            for g, a, s, n in r:
                align = 1
                while align < s and align < 32:
                    align *= 2
                if a % align:
                    errors.append("common %s at %08x violates LINK alignment %d" % (n, a, align))
                if prev_end is not None and a - prev_end >= align:
                    errors.append("gap before common %s (%08x) is larger than its alignment" % (n, a))
                prev_end = a + s
    for g, a, s, n in rows:
        if g == "field" and container(rows, a, s) is None:
            errors.append("field %s at %08x (+%d) is not inside a plain/common variable" % (n, a, s))
    for g, a, s, n in rows:
        if n in names:
            errors.append("duplicate name " + n)
        names.add(n)
    return errors


def generate(rows):
    out = ["; Generated by tools/gen_game_bss.py from asm/game_bss.txt - do not edit.", ".data?"]
    plain = [x for x in rows if x[0] == "plain"]
    for g, a, s, n in plain:
        out.append("public _%s" % n)
    prev = None
    for g, a, s, n in plain:
        if prev is not None and a > prev:
            out.append("        db %d dup(?)" % (a - prev))
        out.append("_%-40s db %d dup(?)   ; %08X" % (n, s, a))
        prev = a + s
    for g, a, s, n in reversed([x for x in rows if x[0] == "common"]):
        out.append("COMM _%s:BYTE:%d   ; %08X" % (n, s, a))
    for g, a, s, n in rows:
        if g != "field":
            continue
        cg, ca, cn = container(rows, a, s)
        out.append("public _%s" % n)
        if cg == "plain":
            out.append("_%-40s equ _%s + %d   ; %08X" % (n, cn, a - ca, a))
        else:
            out.append("_%-40s equ 0%Xh   ; %s + 0x%x" % (n, a, cn, a - ca))
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    src, dst = sys.argv[1], sys.argv[2]
    rows = load(src)
    errs = check(rows)
    if errs:
        print("game_bss.txt: %d layout problem(s)%s" % (len(errs), "" if "-v" in sys.argv else " (use -v to list)"))
        if "-v" in sys.argv:
            print("\n".join(errs))
        if "--strict" in sys.argv:
            sys.exit(1)
    open(dst, "w").write(generate(rows))
