/*
 * resources.c - the resources of rsrc/kgt2nd.rc, compiled in as C data.
 *
 * GENERATED by tools/gen_resources.py from rsrc/kgt2nd.rc - edit the .rc and rerun it.
 *
 * This branch is built by the C compiler alone (no resource compiler), so the executable has no
 * .rsrc section: the bitmaps and the icon are the files of rsrc/assets/ (#embed), the menu and the
 * dialogs the binary templates a resource compiler would have produced.  The functions at the end
 * stand in for FindResource/LoadResource/LockResource, LoadIcon, LoadMenu and DialogBoxParam
 * (main.c, dialogs.c and online.c call them).  VERSIONINFO is not included.
 */
#include "kgt.h"

/* BITMAP RC_BMP_01: the .bmp file; the resource is what follows its 14-byte BITMAPFILEHEADER.
   Two leading bytes keep that BITMAPINFOHEADER 4-byte aligned. */
static const BYTE gcRc_RC_BMP_01[] __attribute__((aligned(4))) = {
    0, 0,
#embed "../rsrc/assets/RC_BMP_01.bmp"
};

/* BITMAP RC_BMP_02: the .bmp file; the resource is what follows its 14-byte BITMAPFILEHEADER.
   Two leading bytes keep that BITMAPINFOHEADER 4-byte aligned. */
static const BYTE gcRc_RC_BMP_02[] __attribute__((aligned(4))) = {
    0, 0,
#embed "../rsrc/assets/RC_BMP_02.bmp"
};

/* BITMAP RC_BMP_03: the .bmp file; the resource is what follows its 14-byte BITMAPFILEHEADER.
   Two leading bytes keep that BITMAPINFOHEADER 4-byte aligned. */
static const BYTE gcRc_RC_BMP_03[] __attribute__((aligned(4))) = {
    0, 0,
#embed "../rsrc/assets/RC_BMP_03.bmp"
};

/* BITMAP RC_BMP_TEXT: the .bmp file; the resource is what follows its 14-byte BITMAPFILEHEADER.
   Two leading bytes keep that BITMAPINFOHEADER 4-byte aligned. */
static const BYTE gcRc_RC_BMP_TEXT[] __attribute__((aligned(4))) = {
    0, 0,
#embed "../rsrc/assets/RC_BMP_TEXT.bmp"
};

/* ICON EXE_ICO: the .ico file (ICONDIR, ICONDIRENTRY[], images) */
static const BYTE gcRc_EXE_ICO[] __attribute__((aligned(4))) = {
#embed "../rsrc/assets/EXE_ICO.ico"
};

/* MENU CUPID_MENU: MENUITEMTEMPLATEHEADER and MENUITEMTEMPLATEs (MF_POPUP 0x10, MF_END 0x80 on the
   last item of each level), texts in UTF-16 */
static const WORD gwRc_CUPID_MENU[] __attribute__((aligned(4))) = {
    0x0000, 0x0000,  /* MENUITEMTEMPLATEHEADER: version 0, offset 0 */
    0x0010, '&', 'W', 'i', 'n', 'd', 'o', 'w', 0x0000,  /* POPUP "&Window" */
    0x0000, 0x0911, '&', 'W', 'i', 'n', 'd', 'o', 'w', 'S', 'i', 'z', 'e', ' ', '1', 'x', '1', 0x0000,  /*     MENUITEM "&WindowSize 1x1", 2321 */
    0x0080, 0x0910, '&', 'F', 'u', 'l', 'l', ' ', 'S', 'c', 'r', 'e', 'e', 'n', 0x0009, 'F', '4', 0x0000,  /*     MENUITEM "&Full Screen\tF4", 2320 */
    0x0010, '&', 'O', 'p', 't', 'i', 'o', 'n', 0x0000,  /* POPUP "&Option" */
    0x0000, 0x091f, '&', 'G', 'a', 'm', 'e', 0x0000,  /*     MENUITEM "&Game", 2335 */
    0x0000, 0x09c5, '&', 'K', 'e', 'y', 'B', 'o', 'a', 'r', 'd', 0x0000,  /*     MENUITEM "&KeyBoard", 2501 */
    0x0080, 0x09c6, '&', 'J', 'o', 'y', 'S', 't', 'i', 'c', 'k', 0x0000,  /*     MENUITEM "&JoyStick", 2502 */
    0x0090, 'H', 'e', 'l', 'p', '(', '&', 'H', ')', 0x0000,  /* POPUP "Help(&H)" */
    0x0080, 0x0839, '&', 'A', 'b', 'o', 'u', 't', 0x0000,  /*     MENUITEM "&About", 2105 */
};

/* DIALOG ABOUT_DLG: DLGTEMPLATE and DWORD-aligned DLGITEMTEMPLATEs (style, extended style, x, y, cx, cy,
   id, class (0xffff + atom: 0x80 Button, 0x81 Edit, 0x82 Static, 0x83 ListBox, 0x85 ComboBox),
   text, 0 bytes of creation data), texts in UTF-16 as the original's (see the .rc) */
static const WORD gwRc_ABOUT_DLG[] __attribute__((aligned(4))) = {
    0x00c0, 0x9000, 0x0000, 0x0000,  /* DLGTEMPLATE: style 0x900000C0, no extended style */
    0x0004, 0x0000, 0x0000, 0x00c8, 0x0050,  /* 4 controls; x, y, cx, cy */
    0x0000,  /* no menu */
    0x0000,  /* default dialog class */
    0x0000,  /* no caption */
    0x0009, '-', '3', ' ', '0', 0x00b4, 0x00b7, 0x00c3, 0x00af, 0x0000,  /* FONT 9, (face name) */
    0x0003, 0x5000, 0x0000, 0x0000, 0x0008, 0x0008, 0x0000, 0x0000, 0x0000, 0xffff, 0x0082, 'e', 'x', 'e', '_', 'i', 'c', 'o', 0x0000, 0x0000,  /* CONTROL "exe_ico", 0, "Static", 0x50000003, 8, 8, 0, 0 */
    0x0001, 0x5002, 0x0000, 0x0000, ' ', 0x000c, 0x0084, 0x0018, 0xffff, 0xffff, 0x0082, 'F', 'i', 'g', 'h', 't', 'e', 'r', ' ', 'M', 'a', 'k', 'e', 'r', '2', 'n', 'd', '.', ' ', 0x000a, '(', 'V', 'e', 'r', ' ', '1', '.', '0', '2', '.', '0', '0', ')', 0x0000, 0x0000,  /* CONTROL "Fighter Maker2nd. ?(Ver 1.02.00)", 65535, "Static", 0x50020001, 32, 12, 132, 24 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, ' ', '(', 0x0084, 0x000c, 0xffff, 0xffff, 0x0082, '(', 'C', ')', '2', '0', '0', '1', ' ', 'E', 'N', 'T', 'E', 'R', 'B', 'R', 'A', 'I', 'N', ',', 'I', 'N', 'C', ' ', '/', ' ', 'O', 'U', 'T', 'B', 'A', 'C', 'K', 0x0000, 0x0000,  /* CONTROL "(C)2001 ENTERBRAIN,INC / OUTBACK", 65535, "Static", 0x50020001, 32, 40, 132, 12 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5001, 0x0000, 0x0000, 'F', '<', '<', 0x000e, 0x07da, 0xffff, 0x0080, 'O', 'K', 0x0000, 0x0000,  /* CONTROL "OK", 2010, "Button", 0x50010001, 70, 60, 60, 14 */
};

/* DIALOG DIALOG_GAMESPEEDSETUP: DLGTEMPLATE and DWORD-aligned DLGITEMTEMPLATEs (style, extended style, x, y, cx, cy,
   id, class (0xffff + atom: 0x80 Button, 0x81 Edit, 0x82 Static, 0x83 ListBox, 0x85 ComboBox),
   text, 0 bytes of creation data), texts in UTF-16 as the original's (see the .rc) */
static const WORD gwRc_DIALOG_GAMESPEEDSETUP[] __attribute__((aligned(4))) = {
    0x00c0, 0x80c8, 0x0000, 0x0000,  /* DLGTEMPLATE: style 0x80C800C0, no extended style */
    0x0019, 0x0000, 0x0000, 0x00b6, 0x010a,  /* 25 controls; x, y, cx, cy */
    0x0000,  /* no menu */
    0x0000,  /* default dialog class */
    'G', 'a', 'm', 'e', ' ', 'S', 'e', 't', 't', 'i', 'n', 'g', 0x0000,  /* CAPTION "Game Setting" */
    0x0009, '-', '3', ' ', '0', 0x00b4, 0x00b7, 0x00c3, 0x00af, 0x0000,  /* FONT 9, (face name) */
    0x0001, 0x5001, 0x0000, 0x0000, 'H', 0x00f8, '2', 0x000e, 0x07da, 0xffff, 0x0080, 'O', 'k', 0x0000, 0x0000,  /* CONTROL "Ok", 2010, "Button", 0x50010001, 72, 248, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x007f, 0x00f8, '2', 0x000e, 0x07dd, 0xffff, 0x0080, 'C', 'a', 'n', 'c', 'e', 'l', 0x0000, 0x0000,  /* CONTROL "Cancel", 2013, "Button", 0x50010000, 127, 248, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x0008, 0x00b0, '(', 0xffff, 0xffff, 0x0080, 'S', 'e', 'l', 'e', 'c', 't', ' ', 'B', 'G', '(', 'V', 'S', '.', ')', 0x0000, 0x0000,  /* CONTROL "Select BG(VS.)", 65535, "Button", 0x50000007, 4, 8, 176, 40 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 'H', 0x0010, 'h', 0x001e, 0xffff, 0xffff, 0x0080, 'B', 'G', 0x0000, 0x0000,  /* CONTROL "BG", 65535, "Button", 0x50000007, 72, 16, 104, 30 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0203, 0x5021, 0x0000, 0x0000, 'L', 0x001c, '`', 0x00c8, 0x36b1, 0xffff, 0x0085, 0x0000, 0x0000,  /* CONTROL "", 14001, "ComboBox", 0x50210203, 76, 28, 96, 200 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, '4', 0x00b0, 0x001e, 0xffff, 0xffff, 0x0080, '#', ' ', 'o', 'f', ' ', 'R', 'o', 'u', 'n', 'd', 's', '(', 'V', 'S', '.', ')', 0x0000, 0x0000,  /* CONTROL "# of Rounds(VS.)", 65535, "Button", 0x50000007, 4, 52, 176, 30 */
    0x0000,  /* (padding to a DWORD boundary) */
    '9', 0x5001, 0x0000, 0x0000, '0', '@', 'd', 0x000f, 0x07e4, 'm', 's', 'c', 't', 'l', 's', '_', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'r', '3', '2', 0x0000, 'S', 'l', 'i', 'd', 'e', 'r', '2', 0x0000, 0x0000,  /* CONTROL "Slider2", 2020, "msctls_trackbar32", 0x50010039, 48, 64, 100, 15 */
    0x1201, 0x5002, 0x0000, 0x0000, 0x0095, '>', 0x0019, 0x000f, 0x07e5, 0xffff, 0x0082, 0x0000, 0x0000,  /* CONTROL "", 2021, "Static", 0x50021201, 149, 62, 25, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 'T', 0x00b0, 0x001e, 0xffff, 0xffff, 0x0080, '#', ' ', 'o', 'f', ' ', 'R', 'o', 'u', 'n', 'd', 's', ' ', 'T', 'e', 'a', 'm', ' ', 'V', 'S', 0x0000, 0x0000,  /* CONTROL "# of Rounds Team VS", 65535, "Button", 0x50000007, 4, 84, 176, 30 */
    '9', 0x5001, 0x0000, 0x0000, '0', '`', 'd', 0x000f, 0x07e2, 'm', 's', 'c', 't', 'l', 's', '_', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'r', '3', '2', 0x0000, 'S', 'l', 'i', 'd', 'e', 'r', '2', 0x0000, 0x0000,  /* CONTROL "Slider2", 2018, "msctls_trackbar32", 0x50010039, 48, 96, 100, 15 */
    0x1201, 0x5002, 0x0000, 0x0000, 0x0095, '^', 0x0019, 0x000f, 0x07e3, 0xffff, 0x0082, 0x0000, 0x0000,  /* CONTROL "", 2019, "Static", 0x50021201, 149, 94, 25, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, '|', 0x00b0, 0x001e, 0xffff, 0xffff, 0x0080, 'S', 'p', 'e', 'e', 'd', 0x0000, 0x0000,  /* CONTROL "Speed", 65535, "Button", 0x50000007, 4, 124, 176, 30 */
    '9', 0x5001, 0x0000, 0x0000, 0x0018, 0x0089, 'd', 0x000f, 0x07de, 'm', 's', 'c', 't', 'l', 's', '_', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'r', '3', '2', 0x0000, 'S', 'l', 'i', 'd', 'e', 'r', '2', 0x0000, 0x0000,  /* CONTROL "Slider2", 2014, "msctls_trackbar32", 0x50010039, 24, 137, 100, 15 */
    0x1201, 0x5002, 0x0000, 0x0000, 0x0095, 0x0086, 0x0019, 0x000f, 0x07df, 0xffff, 0x0082, 0x0000, 0x0000,  /* CONTROL "", 2015, "Static", 0x50021201, 149, 134, 25, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x00a0, 0x00b0, 0x001e, 0xffff, 0xffff, 0x0080, 'T', 'i', 'm', 'e', 'r', 0x0000, 0x0000,  /* CONTROL "Timer", 65535, "Button", 0x50000007, 4, 160, 176, 30 */
    '9', 0x5001, 0x0000, 0x0000, 0x0018, 0x00ad, 'd', 0x000f, 0x07e0, 'm', 's', 'c', 't', 'l', 's', '_', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'r', '3', '2', 0x0000, 'S', 'l', 'i', 'd', 'e', 'r', '2', 0x0000, 0x0000,  /* CONTROL "Slider2", 2016, "msctls_trackbar32", 0x50010039, 24, 173, 100, 15 */
    0x1201, 0x5002, 0x0000, 0x0000, 0x0095, 0x00aa, 0x0019, 0x000f, 0x07e1, 0xffff, 0x0082, 0x0000, 0x0000,  /* CONTROL "", 2017, "Static", 0x50021201, 149, 170, 25, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0009, 0x0086, 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '+', 0x0000, 0x0000,  /* CONTROL "+", 65535, "Static", 0x50020201, 9, 134, 10, 15 */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0081, 0x0086, 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '-', 0x0000, 0x0000,  /* CONTROL "-", 65535, "Static", 0x50020201, 129, 134, 10, 15 */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x00c8, 0x00b0, '*', 0xffff, 0xffff, 0x0080, 'J', 'o', 'y', 's', 't', 'i', 'c', 'k', 0x0000, 0x0000,  /* CONTROL "Joystick", 65535, "Button", 0x50000007, 4, 200, 176, 42 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0003, 0x5001, 0x0000, 0x0000, 0x000c, 0x00d4, '7', 0x000f, 0x32cb, 0xffff, 0x0080, 'J', 'o', 'y', 'S', 't', 'i', 'c', 'k', 0x0000, 0x0000,  /* CONTROL "JoyStick", 13003, "Button", 0x50010003, 12, 212, 55, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0009, 0x00aa, 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '-', 0x0000, 0x0000,  /* CONTROL "-", 65535, "Static", 0x50020201, 9, 170, 10, 15 */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0081, 0x00aa, 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '+', 0x0000, 0x0000,  /* CONTROL "+", 65535, "Static", 0x50020201, 129, 170, 10, 15 */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0009, '^', '#', 0x000f, 0xffff, 0xffff, 0x0082, 'R', 'o', 'u', 'n', 'd', 's', 0x0000, 0x0000,  /* CONTROL "Rounds", 65535, "Static", 0x50020201, 9, 94, 35, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0009, '>', '#', 0x000f, 0xffff, 0xffff, 0x0082, 'R', 'o', 'u', 'n', 'd', 's', 0x0000, 0x0000, 0x0000,  /* CONTROL "Rounds?", 65535, "Static", 0x50020201, 9, 62, 35, 15 */
};

/* DIALOG DIALOG_GAMESPEEDSETUP2: DLGTEMPLATE and DWORD-aligned DLGITEMTEMPLATEs (style, extended style, x, y, cx, cy,
   id, class (0xffff + atom: 0x80 Button, 0x81 Edit, 0x82 Static, 0x83 ListBox, 0x85 ComboBox),
   text, 0 bytes of creation data), texts in UTF-16 as the original's (see the .rc) */
static const WORD gwRc_DIALOG_GAMESPEEDSETUP2[] __attribute__((aligned(4))) = {
    0x00c0, 0x80c8, 0x0000, 0x0000,  /* DLGTEMPLATE: style 0x80C800C0, no extended style */
    0x0012, 0x0000, 0x0000, 0x00b6, 0x010a,  /* 18 controls; x, y, cx, cy */
    0x0000,  /* no menu */
    0x0000,  /* default dialog class */
    'T', 'e', 's', 't', ' ', 'S', 'e', 't', 't', 'i', 'n', 'g', 0x0000,  /* CAPTION "Test Setting" */
    0x0009, '-', '3', ' ', '0', 0x00b4, 0x00b7, 0x00c3, 0x00af, 0x0000,  /* FONT 9, (face name) */
    0x0001, 0x5001, 0x0000, 0x0000, 'H', 0x00f8, '2', 0x000e, 0x07da, 0xffff, 0x0080, 'O', 'k', 0x0000, 0x0000,  /* CONTROL "Ok", 2010, "Button", 0x50010001, 72, 248, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x007f, 0x00f8, '2', 0x000e, 0x07dd, 0xffff, 0x0080, 'C', 'a', 'n', 'c', 'e', 'l', 0x0000, 0x0000,  /* CONTROL "Cancel", 2013, "Button", 0x50010000, 127, 248, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0005, 'A', 'U', 0x001e, 0xffff, 0xffff, 0x0080, 'B', 'G', 0x0000, 0x0000,  /* CONTROL "BG", 65535, "Button", 0x50000007, 5, 65, 85, 30 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0203, 0x5021, 0x0000, 0x0000, 0x000a, 'L', 'K', 0x00c8, 0x36b1, 0xffff, 0x0085, 0x0000, 0x0000,  /* CONTROL "", 14001, "ComboBox", 0x50210203, 10, 76, 75, 200 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 'd', 0x00af, 0x001e, 0xffff, 0xffff, 0x0080, 'S', 'p', 'e', 'e', 'd', 0x0000, 0x0000,  /* CONTROL "Speed", 65535, "Button", 0x50000007, 4, 100, 175, 30 */
    '9', 0x5001, 0x0000, 0x0000, 0x0018, 'n', 'd', 0x000f, 0x07de, 'm', 's', 'c', 't', 'l', 's', '_', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'r', '3', '2', 0x0000, 'S', 'l', 'i', 'd', 'e', 'r', '2', 0x0000, 0x0000,  /* CONTROL "Slider2", 2014, "msctls_trackbar32", 0x50010039, 24, 110, 100, 15 */
    0x1201, 0x5002, 0x0000, 0x0000, 0x0095, 'n', 0x0019, 0x000f, 0x07df, 0xffff, 0x0082, 0x0000, 0x0000,  /* CONTROL "", 2015, "Static", 0x50021201, 149, 110, 25, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0009, 'n', 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '+', 0x0000, 0x0000,  /* CONTROL "+", 65535, "Static", 0x50020201, 9, 110, 10, 15 */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0081, 'n', 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '-', 0x0000, 0x0000,  /* CONTROL "-", 65535, "Static", 0x50020201, 129, 110, 10, 15 */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x00ac, 0x00af, 'F', 0xffff, 0xffff, 0x0080, 'O', 't', 'h', 'e', 'r', 0x0000, 0x0000,  /* CONTROL "Other", 65535, "Button", 0x50000007, 4, 172, 175, 70 */
    0x0003, 0x5001, 0x0000, 0x0000, 0x0009, 0x00b6, 'F', 0x000f, 0x32c9, 0xffff, 0x0080, 'D', 'i', 's', 'p', 'l', 'a', 'y', ' ', 'H', 'i', 't', ' ', 'B', 'o', 'x', 'e', 's', 0x0000, 0x0000,  /* CONTROL "Display Hit Boxes", 13001, "Button", 0x50010003, 9, 182, 70, 15 */
    0x0003, 0x5001, 0x0000, 0x0000, 0x0009, 0x00ca, '7', 0x000f, 0x32ca, 0xffff, 0x0080, 'D', 'i', 's', 'p', 'l', 'a', 'y', ' ', 'F', 'P', 'S', 0x0000, 0x0000,  /* CONTROL "Display FPS", 13002, "Button", 0x50010003, 9, 202, 55, 15 */
    0x0003, 0x5001, 0x0000, 0x0000, 0x0009, 0x00de, '7', 0x000f, 0x32cb, 0xffff, 0x0080, 'J', 'o', 'y', 'S', 't', 'i', 'c', 'k', 0x0000, 0x0000,  /* CONTROL "JoyStick", 13003, "Button", 0x50010003, 9, 222, 55, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x0088, 0x00af, 0x001e, 0xffff, 0xffff, 0x0080, 'T', 'i', 'm', 'e', 'r', 0x0000, 0x0000,  /* CONTROL "Timer", 65535, "Button", 0x50000007, 4, 136, 175, 30 */
    '9', 0x5001, 0x0000, 0x0000, 0x0018, 0x0092, 'd', 0x000f, 0x07e0, 'm', 's', 'c', 't', 'l', 's', '_', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'r', '3', '2', 0x0000, 'S', 'l', 'i', 'd', 'e', 'r', '2', 0x0000, 0x0000,  /* CONTROL "Slider2", 2016, "msctls_trackbar32", 0x50010039, 24, 146, 100, 15 */
    0x1201, 0x5002, 0x0000, 0x0000, 0x0095, 0x0092, 0x0019, 0x000f, 0x07e1, 0xffff, 0x0082, 0x0000, 0x0000,  /* CONTROL "", 2017, "Static", 0x50021201, 149, 146, 25, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0009, 0x0092, 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '-', 0x0000, 0x0000,  /* CONTROL "-", 65535, "Static", 0x50020201, 9, 146, 10, 15 */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0081, 0x0092, 0x000a, 0x000f, 0xffff, 0xffff, 0x0082, '+', 0x0000, 0x0000,  /* CONTROL "+", 65535, "Static", 0x50020201, 129, 146, 10, 15 */
};

/* DIALOG DIALOG_SETUP_JOYSTICK: DLGTEMPLATE and DWORD-aligned DLGITEMTEMPLATEs (style, extended style, x, y, cx, cy,
   id, class (0xffff + atom: 0x80 Button, 0x81 Edit, 0x82 Static, 0x83 ListBox, 0x85 ComboBox),
   text, 0 bytes of creation data), texts in UTF-16 as the original's (see the .rc) */
static const WORD gwRc_DIALOG_SETUP_JOYSTICK[] __attribute__((aligned(4))) = {
    0x00c0, 0x80c8, 0x0000, 0x0000,  /* DLGTEMPLATE: style 0x80C800C0, no extended style */
    0x0029, 0x0000, 0x0000, 0x0143, 0x00c0,  /* 41 controls; x, y, cx, cy */
    0x0000,  /* no menu */
    0x0000,  /* default dialog class */
    'J', 'o', 'y', 'S', 't', 'i', 'c', 'k', 0x0000,  /* CAPTION "JoyStick" */
    0x0009, '-', '3', ' ', '0', 0x00b4, 0x00b7, 0x00c3, 0x00af, 0x0000,  /* FONT 9, (face name) */
    0x0001, 0x5001, 0x0000, 0x0000, 0x00d7, 0x009b, '2', 0x000e, 0x0001, 0xffff, 0x0080, 'O', 'K', 0x0000, 0x0000,  /* CONTROL "OK", 1, "Button", 0x50010001, 215, 155, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x010e, 0x009b, '2', 0x000e, 0x0002, 0xffff, 0x0080, 'C', 'a', 'n', 'c', 'e', 'l', 0x0000, 0x0000,  /* CONTROL "Cancel", 2, "Button", 0x50010000, 270, 155, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0005, 0x0005, 0x013b, 'F', 0xffff, 0xffff, 0x0080, 'P', 'l', 'a', 'y', 'e', 'r', ' ', '1', 0x0000, 0x0000,  /* CONTROL "Player 1", 65535, "Button", 0x50000007, 5, 5, 315, 70 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, '#', 0x000f, '-', 0x000f, 0x03e9, 0xffff, 0x0080, 'U', 'p', 0x0000, 0x0000,  /* CONTROL "Up", 1001, "Button", 0x58010000, 35, 15, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, 0x000a, '#', '-', 0x000f, 0x03ea, 0xffff, 0x0080, 'L', 'e', 'f', 't', 0x0000, 0x0000,  /* CONTROL "Left", 1002, "Button", 0x58010000, 10, 35, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, '#', '7', '-', 0x000f, 0x03eb, 0xffff, 0x0080, 'D', 'o', 'w', 'n', 0x0000, 0x0000,  /* CONTROL "Down", 1003, "Button", 0x58010000, 35, 55, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, '=', '#', '-', 0x000f, 0x03ec, 0xffff, 0x0080, 'R', 'i', 'g', 'h', 't', 0x0000, 0x0000,  /* CONTROL "Right", 1004, "Button", 0x58010000, 61, 35, 45, 15 */
    0x0000, 0x5001, 0x0000, 0x0000, 's', '7', '-', 0x000f, 0x03ed, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1005, "Button", 0x50010000, 115, 55, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00a5, '7', '-', 0x000f, 0x03ee, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1006, "Button", 0x50010000, 165, 55, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00d7, '7', '-', 0x000f, 0x03ef, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1007, "Button", 0x50010000, 215, 55, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 's', 0x0019, '-', 0x000f, 0x03f0, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1008, "Button", 0x50010000, 115, 25, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00a5, 0x0019, '-', 0x000f, 0x03f1, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1009, "Button", 0x50010000, 165, 25, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00d7, 0x0019, '-', 0x000f, 0x03f2, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1010, "Button", 0x50010000, 215, 25, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 's', '-', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'A', 0x0000, 0x0000,  /* CONTROL "A", 65535, "Static", 0x50020001, 115, 45, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00a5, '-', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'B', 0x0000, 0x0000,  /* CONTROL "B", 65535, "Static", 0x50020001, 165, 45, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00d7, '-', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'C', 0x0000, 0x0000,  /* CONTROL "C", 65535, "Static", 0x50020001, 215, 45, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 's', 0x000f, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'D', 0x0000, 0x0000,  /* CONTROL "D", 65535, "Static", 0x50020001, 115, 15, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00a5, 0x000f, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'E', 0x0000, 0x0000,  /* CONTROL "E", 65535, "Static", 0x50020001, 165, 15, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00d7, 0x000f, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'F', 0x0000, 0x0000,  /* CONTROL "F", 65535, "Static", 0x50020001, 215, 15, 45, 10 */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0005, 'P', 0x013b, 'H', 0xffff, 0xffff, 0x0080, 'P', 'l', 'a', 'y', 'e', 'r', ' ', '2', 0x0000, 0x0000,  /* CONTROL "Player 2", 65535, "Button", 0x50000007, 5, 80, 315, 72 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, '#', 'Z', '-', 0x000f, 0x03ff, 0xffff, 0x0080, 'U', 'p', 0x0000, 0x0000,  /* CONTROL "Up", 1023, "Button", 0x58010000, 35, 90, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, 0x000a, 'n', '-', 0x000f, 0x03f4, 0xffff, 0x0080, 'L', 'e', 'f', 't', 0x0000, 0x0000,  /* CONTROL "Left", 1012, "Button", 0x58010000, 10, 110, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, '#', 0x0082, '-', 0x000f, 0x03f5, 0xffff, 0x0080, 'D', 'o', 'w', 'n', 0x0000, 0x0000,  /* CONTROL "Down", 1013, "Button", 0x58010000, 35, 130, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5801, 0x0000, 0x0000, '=', 'n', '-', 0x000f, 0x03f6, 0xffff, 0x0080, 'R', 'i', 'g', 'h', 't', 0x0000, 0x0000,  /* CONTROL "Right", 1014, "Button", 0x58010000, 61, 110, 45, 15 */
    0x0000, 0x5001, 0x0000, 0x0000, 's', 0x0082, '-', 0x000f, 0x0401, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1025, "Button", 0x50010000, 115, 130, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00a5, 0x0082, '-', 0x000f, 0x0402, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1026, "Button", 0x50010000, 165, 130, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00d7, 0x0082, '-', 0x000f, 0x0403, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1027, "Button", 0x50010000, 215, 130, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 's', 'd', '-', 0x000f, 0x0404, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1028, "Button", 0x50010000, 115, 100, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00a5, 'd', '-', 0x000f, 0x0405, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1029, "Button", 0x50010000, 165, 100, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00d7, 'd', '-', 0x000f, 0x0406, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1030, "Button", 0x50010000, 215, 100, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 's', 'x', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'A', 0x0000, 0x0000,  /* CONTROL "A", 65535, "Static", 0x50020001, 115, 120, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00a5, 'x', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'B', 0x0000, 0x0000,  /* CONTROL "B", 65535, "Static", 0x50020001, 165, 120, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00d7, 'x', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'C', 0x0000, 0x0000,  /* CONTROL "C", 65535, "Static", 0x50020001, 215, 120, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 's', 'Z', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'D', 0x0000, 0x0000,  /* CONTROL "D", 65535, "Static", 0x50020001, 115, 90, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00a5, 'Z', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'E', 0x0000, 0x0000,  /* CONTROL "E", 65535, "Static", 0x50020001, 165, 90, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00d7, 'Z', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'F', 0x0000, 0x0000,  /* CONTROL "F", 65535, "Static", 0x50020001, 215, 90, 45, 10 */
    0x0000, 0x5001, 0x0000, 0x0000, 0x010e, 0x0019, '-', 0x000f, 0x03f3, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1011, "Button", 0x50010000, 270, 25, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 0x010e, 0x000f, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'P', 'A', 'U', 'S', 'E', 0x0000, 0x0000,  /* CONTROL "PAUSE", 65535, "Static", 0x50020001, 270, 15, 45, 10 */
    0x0000, 0x5001, 0x0000, 0x0000, 0x010e, 'd', '-', 0x000f, 0x0407, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1031, "Button", 0x50010000, 270, 100, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 0x010e, 'Z', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'P', 'A', 'U', 'S', 'E', 0x0000, 0x0000,  /* CONTROL "PAUSE", 65535, "Static", 0x50020001, 270, 90, 45, 10 */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0005, 0x009b, '2', 0x000e, 0x07db, 0xffff, 0x0080, 'D', 'e', 'f', 'a', 'u', 'l', 't', 0x0000, 0x0000,  /* CONTROL "Default", 2011, "Button", 0x50010000, 5, 155, 50, 14 */
};

/* DIALOG DIALOG_SETUP_KEYBOARD: DLGTEMPLATE and DWORD-aligned DLGITEMTEMPLATEs (style, extended style, x, y, cx, cy,
   id, class (0xffff + atom: 0x80 Button, 0x81 Edit, 0x82 Static, 0x83 ListBox, 0x85 ComboBox),
   text, 0 bytes of creation data), texts in UTF-16 as the original's (see the .rc) */
static const WORD gwRc_DIALOG_SETUP_KEYBOARD[] __attribute__((aligned(4))) = {
    0x00c0, 0x80c8, 0x0000, 0x0000,  /* DLGTEMPLATE: style 0x80C800C0, no extended style */
    0x0031, 0x0000, 0x0000, 0x0157, 0x00c0,  /* 49 controls; x, y, cx, cy */
    0x0000,  /* no menu */
    0x0000,  /* default dialog class */
    'K', 'e', 'y', 'B', 'o', 'a', 'r', 'd', 0x0000,  /* CAPTION "KeyBoard" */
    0x0009, '-', '3', ' ', '0', 0x00b4, 0x00b7, 0x00c3, 0x00af, 0x0000,  /* FONT 9, (face name) */
    0x0001, 0x5001, 0x0000, 0x0000, 0x00e6, 0x00af, '2', 0x000e, 0x0001, 0xffff, 0x0080, 'O', 'K', 0x0000, 0x0000,  /* CONTROL "OK", 1, "Button", 0x50010001, 230, 175, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x011d, 0x00af, '2', 0x000e, 0x0002, 0xffff, 0x0080, 'C', 'a', 'n', 'c', 'e', 'l', 0x0000, 0x0000,  /* CONTROL "Cancel", 2, "Button", 0x50010000, 285, 175, 50, 14 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0005, 0x0005, 0x014f, 'P', 0xffff, 0xffff, 0x0080, 'P', 'l', 'a', 'y', 'e', 'r', ' ', '1', 0x0000, 0x0000,  /* CONTROL "Player 1", 65535, "Button", 0x50000007, 5, 5, 335, 80 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, '-', 'A', '-', 0x000f, 0x03eb, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1003, "Button", 0x50010000, 45, 65, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 'P', '-', '-', 0x000f, 0x03ec, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1004, "Button", 0x50010000, 80, 45, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, '-', 0x0019, '-', 0x000f, 0x03e9, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1001, "Button", 0x50010000, 45, 25, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x000a, '-', '-', 0x000f, 0x03ea, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1002, "Button", 0x50010000, 10, 45, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0087, 'A', '-', 0x000f, 0x03ed, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1005, "Button", 0x50010000, 135, 65, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00b9, 'A', '-', 0x000f, 0x03ee, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1006, "Button", 0x50010000, 185, 65, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00eb, 'A', '-', 0x000f, 0x03ef, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1007, "Button", 0x50010000, 235, 65, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0087, '#', '-', 0x000f, 0x03f0, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1008, "Button", 0x50010000, 135, 35, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00b9, '#', '-', 0x000f, 0x03f1, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1009, "Button", 0x50010000, 185, 35, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00eb, '#', '-', 0x000f, 0x03f2, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1010, "Button", 0x50010000, 235, 35, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 0x0087, '7', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'A', 0x0000, 0x0000,  /* CONTROL "A", 65535, "Static", 0x50020001, 135, 55, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00b9, '7', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'B', 0x0000, 0x0000,  /* CONTROL "B", 65535, "Static", 0x50020001, 185, 55, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00eb, '7', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'V', 0x0000, 0x0000,  /* CONTROL "V", 65535, "Static", 0x50020001, 235, 55, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x0087, 0x0019, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'D', 0x0000, 0x0000,  /* CONTROL "D", 65535, "Static", 0x50020001, 135, 25, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00b9, 0x0019, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'E', 0x0000, 0x0000,  /* CONTROL "E", 65535, "Static", 0x50020001, 185, 25, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00eb, 0x0019, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'F', 0x0000, 0x0000,  /* CONTROL "F", 65535, "Static", 0x50020001, 235, 25, 45, 10 */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0005, 'Z', 0x014f, 'P', 0xffff, 0xffff, 0x0080, 'P', 'l', 'a', 'y', 'e', 'r', ' ', '2', 0x0000, 0x0000,  /* CONTROL "Player 2", 65535, "Button", 0x50000007, 5, 90, 335, 80 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, '-', 0x0096, '-', 0x000f, 0x03ff, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1023, "Button", 0x50010000, 45, 150, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x000a, 0x0082, '-', 0x000f, 0x03fe, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1022, "Button", 0x50010000, 10, 130, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, '-', 'n', '-', 0x000f, 0x03fd, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1021, "Button", 0x50010000, 45, 110, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 'P', 0x0082, '-', 0x000f, 0x0400, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1024, "Button", 0x50010000, 80, 130, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0087, 0x0096, '-', 0x000f, 0x0401, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1025, "Button", 0x50010000, 135, 150, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00b9, 0x0096, '-', 0x000f, 0x0402, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1026, "Button", 0x50010000, 185, 150, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00eb, 0x0096, '-', 0x000f, 0x0403, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1027, "Button", 0x50010000, 235, 150, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0087, 'x', '-', 0x000f, 0x0404, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1028, "Button", 0x50010000, 135, 120, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00b9, 'x', '-', 0x000f, 0x0405, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1029, "Button", 0x50010000, 185, 120, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x00eb, 'x', '-', 0x000f, 0x0406, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1030, "Button", 0x50010000, 235, 120, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 0x0087, 0x008c, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'A', 0x0000, 0x0000,  /* CONTROL "A", 65535, "Static", 0x50020001, 135, 140, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00b9, 0x008c, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'B', 0x0000, 0x0000,  /* CONTROL "B", 65535, "Static", 0x50020001, 185, 140, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00eb, 0x008c, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'C', 0x0000, 0x0000,  /* CONTROL "C", 65535, "Static", 0x50020001, 235, 140, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x0087, 'n', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'D', 0x0000, 0x0000,  /* CONTROL "D", 65535, "Static", 0x50020001, 135, 110, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00b9, 'n', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'E', 0x0000, 0x0000,  /* CONTROL "E", 65535, "Static", 0x50020001, 185, 110, 45, 10 */
    0x0001, 0x5002, 0x0000, 0x0000, 0x00eb, 'n', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'F', 0x0000, 0x0000,  /* CONTROL "F", 65535, "Static", 0x50020001, 235, 110, 45, 10 */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0017, '#', 0x0011, 0x000a, 0xffff, 0xffff, 0x0082, 'L', 'e', 'f', 't', 0x0000, 0x0000,  /* CONTROL "Left", 65535, "Static", 0x50020201, 23, 35, 17, 10 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, '_', '#', 0x0015, 0x000a, 0xffff, 0xffff, 0x0082, 'R', 'i', 'g', 'h', 't', 0x0000, 0x0000,  /* CONTROL "Right", 65535, "Static", 0x50020201, 95, 35, 21, 10 */
    0x0201, 0x5002, 0x0000, 0x0000, '<', 0x000f, 0x000f, 0x000a, 0xffff, 0xffff, 0x0082, 'U', 'p', 0x0000, 0x0000,  /* CONTROL "Up", 65535, "Static", 0x50020201, 60, 15, 15, 10 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, '9', '7', 0x0013, 0x000a, 0xffff, 0xffff, 0x0082, 'D', 'o', 'w', 'n', 0x0000, 0x0000,  /* CONTROL "Down", 65535, "Static", 0x50020201, 57, 55, 19, 10 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, 0x0019, 'x', 0x000f, 0x000a, 0xffff, 0xffff, 0x0082, 'L', 'e', 'f', 't', 0x0000, 0x0000,  /* CONTROL "Left", 65535, "Static", 0x50020201, 25, 120, 15, 10 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, '_', 'x', 0x0012, 0x000a, 0xffff, 0xffff, 0x0082, 'R', 'i', 'g', 'h', 't', 0x0000, 0x0000,  /* CONTROL "Right", 65535, "Static", 0x50020201, 95, 120, 18, 10 */
    0x0201, 0x5002, 0x0000, 0x0000, '<', 'd', 0x000f, 0x000a, 0xffff, 0xffff, 0x0082, 'U', 'p', 0x0000, 0x0000,  /* CONTROL "Up", 65535, "Static", 0x50020201, 60, 100, 15, 10 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0201, 0x5002, 0x0000, 0x0000, ':', 0x008c, 0x0012, 0x0008, 0xffff, 0xffff, 0x0082, 'D', 'o', 'w', 'n', 0x0000, 0x0000,  /* CONTROL "Down", 65535, "Static", 0x50020201, 58, 140, 18, 8 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0122, 0x0019, '-', 0x000f, 0x03f3, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1011, "Button", 0x50010000, 290, 25, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 0x0122, 0x000f, '-', 0x000a, 0xffff, 0xffff, 0x0082, 'P', 'A', 'U', 'S', 'E', 0x0000, 0x0000,  /* CONTROL "PAUSE", 65535, "Static", 0x50020001, 290, 15, 45, 10 */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0005, 0x00af, '2', 0x000e, 0x07db, 0xffff, 0x0080, 'D', 'e', 'f', 'a', 'u', 'l', 't', 0x0000, 0x0000,  /* CONTROL "Default", 2011, "Button", 0x50010000, 5, 175, 50, 14 */
    0x0000, 0x5001, 0x0000, 0x0000, 0x0122, 'n', '-', 0x000f, 0x0407, 0xffff, 0x0080, 0x0000, 0x0000,  /* CONTROL "", 1031, "Button", 0x50010000, 290, 110, 45, 15 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0001, 0x5002, 0x0000, 0x0000, 0x0122, 'd', '-', 0x000a, 0xffff, 0xffff, 0x0082, 'P', 'A', 'U', 'S', 'E', 0x0000, 0x0000,  /* CONTROL "PAUSE", 65535, "Static", 0x50020001, 290, 100, 45, 10 */
};

/* DIALOG 101: DLGTEMPLATE and DWORD-aligned DLGITEMTEMPLATEs (style, extended style, x, y, cx, cy,
   id, class (0xffff + atom: 0x80 Button, 0x81 Edit, 0x82 Static, 0x83 ListBox, 0x85 ComboBox),
   text, 0 bytes of creation data), texts in UTF-16 as the original's (see the .rc) */
static const WORD gwRc_101[] __attribute__((aligned(4))) = {
    0x00c0, 0x80c8, 0x0000, 0x0000,  /* DLGTEMPLATE: style 0x80C800C0, no extended style */
    0x0009, 0x0000, 0x0000, 0x0096, 0x0112,  /* 9 controls; x, y, cx, cy */
    0x0000,  /* no menu */
    0x0000,  /* default dialog class */
    0x00a5, 0x009a, '-', 0x009a, 0x0000,  /* CAPTION "??-?" */
    0x0009, '-', '3', ' ', '0', 0x00b4, 0x00b7, 0x00c3, 0x00af, 0x0000,  /* FONT 9, (face name) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x0080, 0x0090, 'D', 0x03ed, 0xffff, 0x0080, 0x00e2, 'X', 'n', 0x00b2, 0x00fc, 0x00e0, 'k', 0x00c2, 0x00a0, 'Y', 0x008b, 0x0000, 0x0000,  /* CONTROL "?Xn???k??Y?", 1005, "Button", 0x50000007, 4, 128, 144, 68 */
    0x0080, 0x5081, 0x0000, 0x0000, ',', 0x00d4, 'd', 0x0010, 0x03f0, 0xffff, 0x0081, 0x0000, 0x0000,  /* CONTROL "", 1008, "Edit", 0x50810080, 44, 212, 100, 16 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0101, 0x50a1, 0x0000, 0x0000, 0x0008, 0x008c, 0x005c, '4', 0x03e9, 0xffff, 0x0083, 0x0000, 0x0000,  /* CONTROL "", 1001, "ListBox", 0x50A10101, 8, 140, 92, 52 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 'h', 0x009c, '(', '$', 0x03ef, 0xffff, 0x0080, 0x00c2, 0x00a0, 'Y', 0x008b, 0x0000, 0x0000,  /* CONTROL "??Y?", 1007, "Button", 0x50010000, 104, 156, 40, 36 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x00c8, 0x0090, 'H', 0xffff, 0xffff, 0x0080, 0x00b0, '_', 'k', 0x00b2, 0x00fc, 0x00e0, 0x0092, 0x008b, 0x00cb, 'Y', 0x008b, 0x0000, 0x0000,  /* CONTROL "?_k??????Y?", 65535, "Button", 0x50000007, 4, 200, 144, 72 */
    0x0000, 0x5002, 0x0000, 0x0000, 0x000c, 0x00d8, ' ', 0x000c, 0xffff, 0xffff, 0x0082, 0x00bf, 0x00a4, 0x00c8, 0x00eb, 0x0000, 0x0000,  /* CONTROL "????", 65535, "Static", 0x50020000, 12, 216, 32, 12 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0000, 0x5001, 0x0000, 0x0000, 'h', 0x00e8, '(', '$', 0x03ee, 0xffff, 0x0080, 0x00b0, 0x008f, 0x008b, 0x00cb, 0x0000, 0x0000,  /* CONTROL "????", 1006, "Button", 0x50010000, 104, 232, 40, 36 */
    0x0000,  /* (padding to a DWORD boundary) */
    0x0007, 0x5000, 0x0000, 0x0000, 0x0004, 0x0004, 0x0090, '$', 0xffff, 0xffff, 0x0080, 'J', 0x000d, 'M', 0x0008, 'h', 0x00d2, 'g', 0x0011, 0x0015, 0x0087, 'W', 'O', 0x0089, 'D', '~', 'g', 0x0009, 0x0000, 0x0000,  /* CONTROL "J?M?h?g???WO?D~g?", 65535, "Button", 0x50000007, 4, 4, 144, 36 */
    0x0080, 0x5081, 0x0000, 0x0000, 0x0008, 0x0010, 0x0088, 0x0010, 0x03f1, 0xffff, 0x0081, 0x0000, 0x0000,  /* CONTROL "", 1009, "Edit", 0x50810080, 8, 16, 136, 16 */
};

/* one entry of the resource table */
typedef struct kgtEmbeddedResource {
    LPCSTR szType;      /* RT_BITMAP, RT_ICON (here: a whole .ico file), RT_MENU or RT_DIALOG */
    LPCSTR szName;      /* name as in the .rc (compared without case), or MAKEINTRESOURCE(id) */
    const void *pData;  /* the resource data, as LockResource would return it */
    DWORD dwSize;       /* its size in bytes, as SizeofResource would return it */
} kgtEmbeddedResource;

/* all resources of the .rc except VERSIONINFO */
static const kgtEmbeddedResource gkgtEmbeddedResources[] = {
    { RT_BITMAP, "RC_BMP_01", gcRc_RC_BMP_01 + 2 + sizeof(BITMAPFILEHEADER), sizeof(gcRc_RC_BMP_01) - 2 - sizeof(BITMAPFILEHEADER) },
    { RT_BITMAP, "RC_BMP_02", gcRc_RC_BMP_02 + 2 + sizeof(BITMAPFILEHEADER), sizeof(gcRc_RC_BMP_02) - 2 - sizeof(BITMAPFILEHEADER) },
    { RT_BITMAP, "RC_BMP_03", gcRc_RC_BMP_03 + 2 + sizeof(BITMAPFILEHEADER), sizeof(gcRc_RC_BMP_03) - 2 - sizeof(BITMAPFILEHEADER) },
    { RT_BITMAP, "RC_BMP_TEXT", gcRc_RC_BMP_TEXT + 2 + sizeof(BITMAPFILEHEADER), sizeof(gcRc_RC_BMP_TEXT) - 2 - sizeof(BITMAPFILEHEADER) },
    { RT_ICON, "EXE_ICO", gcRc_EXE_ICO, sizeof(gcRc_EXE_ICO) },
    { RT_MENU, "CUPID_MENU", gwRc_CUPID_MENU, sizeof(gwRc_CUPID_MENU) },
    { RT_DIALOG, "ABOUT_DLG", gwRc_ABOUT_DLG, sizeof(gwRc_ABOUT_DLG) },
    { RT_DIALOG, "DIALOG_GAMESPEEDSETUP", gwRc_DIALOG_GAMESPEEDSETUP, sizeof(gwRc_DIALOG_GAMESPEEDSETUP) },
    { RT_DIALOG, "DIALOG_GAMESPEEDSETUP2", gwRc_DIALOG_GAMESPEEDSETUP2, sizeof(gwRc_DIALOG_GAMESPEEDSETUP2) },
    { RT_DIALOG, "DIALOG_SETUP_JOYSTICK", gwRc_DIALOG_SETUP_JOYSTICK, sizeof(gwRc_DIALOG_SETUP_JOYSTICK) },
    { RT_DIALOG, "DIALOG_SETUP_KEYBOARD", gwRc_DIALOG_SETUP_KEYBOARD, sizeof(gwRc_DIALOG_SETUP_KEYBOARD) },
    { RT_DIALOG, MAKEINTRESOURCEA(101), gwRc_101, sizeof(gwRc_101) },
};

/*
 * FindResourceA + LoadResource + LockResource for the embedded resources.
 * szName: resource name (any case) or MAKEINTRESOURCE(id); szType: RT_BITMAP, RT_ICON, RT_MENU or
 * RT_DIALOG; pdwSize: receives the size (may be NULL).
 * Returns the resource data, or NULL if there is no such resource.
 * Globals: reads gkgtEmbeddedResources.
 */
const void *pLockEmbeddedResource(LPCSTR szName, LPCSTR szType, DWORD *pdwSize)
{
    int i;

    for (i = 0; i < (int)(sizeof(gkgtEmbeddedResources) / sizeof(gkgtEmbeddedResources[0])); i++) {
        const kgtEmbeddedResource *pRes = &gkgtEmbeddedResources[i];

        if (pRes->szType != szType)
            continue;
        if (IS_INTRESOURCE(szName) || IS_INTRESOURCE(pRes->szName)) {
            if (szName != pRes->szName)
                continue;
        } else if (lstrcmpiA(szName, pRes->szName) != 0) {
            continue;
        }
        if (pdwSize)
            *pdwSize = pRes->dwSize;
        return pRes->pData;
    }
    return NULL;
}

/*
 * LoadIconA for the embedded icon: picks the image of the .ico whose size is the system's icon size
 * (else the first one) with the most colours, as LoadIcon would from the icon group, and creates the
 * icon from it (resource format version 0x00030000).
 * szName: icon name.
 * Returns the icon, or NULL.
 */
HICON hLoadEmbeddedIcon(LPCSTR szName)
{
    const BYTE *pIcoFile;       /* the whole .ico file */
    const BYTE *pEntry;         /* its ICONDIRENTRY being looked at */
    const BYTE *pBest;          /* the entry chosen so far */
    int iImages, i, iIconWidth, iIconHeight;

    pIcoFile = pLockEmbeddedResource(szName, RT_ICON, NULL);
    if (pIcoFile == NULL)
        return NULL;
    iIconWidth = GetSystemMetrics(SM_CXICON);
    iIconHeight = GetSystemMetrics(SM_CYICON);
    /* ICONDIR: WORD reserved, WORD type (1), WORD count; ICONDIRENTRY (16 bytes): BYTE width,
       BYTE height, BYTE colours, BYTE reserved, WORD planes, WORD bits, DWORD size, DWORD offset */
    iImages = *(const WORD *)(pIcoFile + 4);
    pBest = NULL;
    for (i = 0; i < iImages; i++) {
        pEntry = pIcoFile + 6 + i * 16;
        /* the first image, replaced by one of the system size (and then by one with more bits per pixel) */
        if (pBest == NULL
            || (pEntry[0] == iIconWidth && pEntry[1] == iIconHeight
                && (pBest[0] != iIconWidth || pBest[1] != iIconHeight || *(const WORD *)(pEntry + 6) > *(const WORD *)(pBest + 6))))
            pBest = pEntry;
    }
    if (pBest == NULL)
        return NULL;
    /* the image's data (BITMAPINFOHEADER, colours, XOR and AND masks) at its offset in the file */
    return CreateIconFromResourceEx((PBYTE)pIcoFile + *(const DWORD *)(pBest + 12), *(const DWORD *)(pBest + 8),
                                    TRUE, 0x00030000, iIconWidth, iIconHeight, LR_DEFAULTCOLOR);
}

/*
 * LoadMenuA for the embedded menu.
 * szName: menu name.
 * Returns the menu, or NULL.
 */
HMENU hLoadEmbeddedMenu(LPCSTR szName)
{
    const void *pTemplate = pLockEmbeddedResource(szName, RT_MENU, NULL);

    return pTemplate ? LoadMenuIndirectA(pTemplate) : NULL;
}

/*
 * DialogBoxParamA with an embedded dialog template.
 * hInstance, hWndParent, pfnDialog, lParam: as for DialogBoxParamA; szTemplate: dialog name or
 * MAKEINTRESOURCE(id).
 * Returns the EndDialog value, or -1 on failure.
 */
INT_PTR iEmbeddedDialogBoxParamA(HINSTANCE hInstance, LPCSTR szTemplate, HWND hWndParent, DLGPROC pfnDialog, LPARAM lParam)
{
    const void *pTemplate = pLockEmbeddedResource(szTemplate, RT_DIALOG, NULL);

    if (pTemplate == NULL)
        return -1;
    return DialogBoxIndirectParamA(hInstance, (LPCDLGTEMPLATEA)pTemplate, hWndParent, pfnDialog, lParam);
}
